# Generated by Django 6.0.4 on 2026-04-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='other', max_length=100),
        ),
    ]
